export const G = {
	ranches: Objects([]),
	poop: Objects([]),
	trees: Objects([]),
	monsters: Objects([]),
	workers: Objects([]),
	fire: Objects([]),
	chickenFood: Objects([]),
	allies: Objects([]),
	turrets: Objects([]),
	money: 20,
	wave: 1,
	pause: false,
	pictures: {},
	Sprite: {},
	Audio: {},
	image: {},
	SpriteLayers: {},
	tilemaps: {},
}
