export const G = {
	ranches: LocalObjects([]),
	poop: LocalObjects([]),
	trees: LocalObjects([]),
	monsters: LocalObjects([]),
	workers: LocalObjects([]),
	fire: LocalObjects([]),
	chickenFood: LocalObjects([]),
	allies: LocalObjects([]),
	turrets: LocalObjects([]),
	money: 20,
	wave: 1,
	pause: false,
	pictures: {},
	Sprite: {},
	Audio: {},
	image: {},
	SpriteLayers: {},
	tilemaps: {},
}
