<<<<<<< HEAD
// Enhance_js_Array()
// Enhance_js_Object()
// Enhance_html()
// Enhance_js_Number()
// Enhance_js_String()
// Enhance_html_WebComponents()
// Enhance_html_collection()
||||||| parent of c82ff414 (quick fix)
Enhance_js_Array()
Enhance_js_Object()
Enhance_html()
Enhance_js_Number()
Enhance_js_String()
Enhance_html_WebComponents()
Enhance_html_collection()
=======
Enhance_js_Array()
Enhance_js_Object()
Enhance_html()
Enhance_js_Number()
Enhance_js_String()
Enhance_html_WebComponents()
Enhance_html_collection()

>>>>>>> c82ff414 (quick fix)

export function EnhanceAll() {
	Enhance_js_Array()
	Enhance_js_Object()
	Enhance_html()
	Enhance_js_Number()
	Enhance_js_String()
	Enhance_html_WebComponents()
	Enhance_html_collection()
}
